// @input: User interaction (Google sign-in in browser window)
// @output: youtube-cookies.txt for yt-dlp authentication
// @position: One-time setup script — run before YouTube downloads work

import { chromium } from 'playwright';
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname } from 'node:path';

const PROXY = process.env.MEDIA_PROXY || process.env.HTTPS_PROXY || 'http://127.0.0.1:7890';
const STATE_DIR = process.env.OMNIAGENT_LOCAL_STATE_DIR?.trim() || `${process.cwd()}/.omniagent-state`;
const COOKIES_PATH = `${STATE_DIR}/youtube-cookies.txt`;
const POLL_MS = 2000;
const TIMEOUT_MS = 5 * 60 * 1000;

function toNetscape(cookies) {
  const lines = ['# Netscape HTTP Cookie File', '# Generated by OmniAgent YouTube Setup'];
  const seen = new Set();
  for (const c of cookies) {
    const key = `${c.domain}:${c.name}`;
    if (seen.has(key)) continue;
    seen.add(key);
    const httpOnly = c.domain.startsWith('.') ? 'TRUE' : 'FALSE';
    const secure = c.secure ? 'TRUE' : 'FALSE';
    const expires = String(Math.floor(c.expires || 0));
    lines.push(`${c.domain}\t${httpOnly}\t${c.path}\t${secure}\t${expires}\t${c.name}\t${c.value}`);
  }
  return lines.join('\n');
}

async function main() {
  console.log('YouTube 认证设置');
  console.log('='.repeat(40));
  console.log(`代理: ${PROXY}`);
  console.log(`Cookie保存: ${COOKIES_PATH}`);
  console.log('');
  console.log('即将打开浏览器，请登录Google账号。');
  console.log('登录完成后会自动检测并保存cookie。');
  console.log('');

  const browser = await chromium.launch({
    headless: false,
    proxy: { server: PROXY },
    channel: 'msedge',
  });

  const ctx = await browser.newContext({ viewport: { width: 1280, height: 800 } });
  const page = await ctx.newPage();
  await page.goto('https://www.youtube.com/', {
    waitUntil: 'domcontentloaded',
    timeout: 60_000,
  });

  console.log('浏览器已打开YouTube，请点击右上角"登录"按钮登录Google账号...');

  const start = Date.now();
  let authenticated = false;

  while (Date.now() - start < TIMEOUT_MS) {
    await new Promise(r => setTimeout(r, POLL_MS));
    try {
      const cookies = await ctx.cookies('https://www.youtube.com');
      const hasSid = cookies.some(c => c.name === '__Secure-1PSID' || c.name === 'SAPISID');
      if (!hasSid) continue;

      console.log('检测到登录cookie，正在验证...');
      await page.goto('https://www.youtube.com/watch?v=jNQXAC9IVRw', {
        waitUntil: 'domcontentloaded',
        timeout: 15_000,
      });
      const status = await page.evaluate(() => window.ytInitialPlayerResponse?.playabilityStatus?.status).catch(() => null);
      if (status === 'OK') {
        authenticated = true;
        break;
      }
      console.log(`验证状态: ${status ?? 'unknown'}，继续等待...`);
    } catch { /* page navigating */ }
  }

  if (!authenticated) {
    await browser.close();
    console.error('超时：未检测到有效的Google登录。');
    process.exit(1);
  }

  // Collect cookies from all relevant domains
  const allCookies = [
    ...await ctx.cookies('https://www.youtube.com'),
    ...await ctx.cookies('https://www.google.com'),
    ...await ctx.cookies('https://accounts.google.com'),
  ];

  mkdirSync(dirname(COOKIES_PATH), { recursive: true });
  writeFileSync(COOKIES_PATH, toNetscape(allCookies), 'utf8');

  await browser.close();
  console.log(`\n已保存 ${allCookies.length} 个cookie到 ${COOKIES_PATH}`);
  console.log('设置完成！现在可以下载YouTube视频了。');
}

main().catch(e => {
  console.error('设置失败:', e.message);
  process.exit(1);
});
